kind: pipeline
type: kubernetes
name: default

workspace:
  path: /drone/src

steps:
- name: build
  image: l.gcr.io/google/bazel:latest
  commands:
  - clang --version
  - "bazel build -s //:LibIni"
